### ISSUE TITLE
Ping Modular Input error with python 3

### ISSUE THREAD

**Issue by zszia** [LukeMurphey/splunk-network-tools#7]
If you run splunk in python3 mode:

server.conf
```
[general]
python.version = python3
```

the ping modular input is throwing a RuntimeError: dictionary changed size during iteration.
I tested it under linux and windows with the same result.

```
2020-08-10 17:00:48,131 ERROR Execution failed
Traceback (most recent call last):
  File "D:\Tools\Splunk\etc\apps\network_tools\bin\modular_input.zip\modular_input\modular_input_base_class.py", line 1095, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "D:\Tools\Splunk\etc\apps\network_tools\bin\modular_input.zip\modular_input\modular_input_base_class.py", line 976, in do_run
    self.run(stanza, cleaned_params, input_config)
  File "D:\Tools\Splunk\etc\apps\network_tools\bin\ping.py", line 179, in run
    self.clean_old_threads()
  File "D:\Tools\Splunk\etc\apps\network_tools\bin\ping.py", line 108, in clean_old_threads
    for thread_stanza in self.threads.keys():
RuntimeError: dictionary changed size during iteration
```

My workaround was to change

```
for thread_stanza in self.threads.keys():
```
to 
```
for thread_stanza in list(self.threads.keys()):
```

in ping.py.

Another problem is, that if you run splunk in mixed mode and try to set the modular input to run with python3, you get an error about unsupported parameter "python.version":

inputs.conf
```
[ping://TestPing]
python.version = python3
```
Thanks for the great app!

**Comment by LukeMurphey** [comment]
Thanks the very detailed report. This has been fixed and is available in version 1.5.1.
